# main text of home
name: Hello!
bio: I build beautiful software experiences

# twitter summary info
description: Aamna's personal website

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: https://aamnakhan.com
# your url: http://USERNAME.github.io


# To enable google analytics, supply your token below
analytics-google: 'UA-44949721-2'

writing: tinybitsofcarbon.com
twitter: _aamnakhan
instagram: khan_saab
linkedin: aamna92
github: aamnakhan
# stackoverflow: 7044681/mystackoverflow
medium: aamnakhan

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need projects, comment the *projects* configs below
# projects: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com/aamnakhan
